### PR TITLE
Add section blog & social media

### PR DESCRIPTION
**Pull request by moodule**
Hello there, here's a little addition to your work :)

This is going towards adding a "community" section with podcasts, blogs, hackathon and everything that keeps people pumped up to do space science!

I'd say that the community (actual people, fiction, broadcast etc) gets people involved at least as much as the hard science, right ?
So it'd qualify as "awesome" too right ? ;)

cheers

### CODE REVIEW

**Comment by cantino** [comment]
I'm undecided if we should link to blogs / profiles. I'm wondering if this site should be more a directory of resources.

**Comment by moodule** [comment]
I agree, I'm going too far with profiles and podcasts, it lacks content.

On the other side there are a few blogs (personal or community driven) that actually have technical content.

The "nuit blanche" blog is good example: it's a central hub for a research / startup community.
A lot of research papers are published there, at the cross road of ML / remote sensing / space.

May-be I can move this to a "research" section of sorts?

**Comment by cantino** [comment]
Sure, I'm fine with that.

**Comment by moodule** [comment]
Hi Cantino (happy new year :D )
In fact, the "nuit blanche" blog is focused on ML / remote sensing, so my PR feels far fetched!
I'm closing it :D

**Comment by cantino** [comment]
Agreed, thanks!

**Pull request closed without merging**
