### PR TITLE
Reorganize the section "other"

### PR DESCRIPTION
**Pull request by moodule**
Hello again,
just moving on with my "community" proposals :)
this time I'm actually proposing to rename the "other" section to "community" and moving its content to more specific sections.

### CODE REVIEW

**Comment by moodule** [comment]
so everything I proposed would go under that "community" section in the overall merge
voilà !

**Comment by cantino** [comment]
Would you mind rebasing this?

**Comment by moodule** [comment]
That should do it!

**Comment by cantino** [comment]
Thanks @moodule :)

**Pull request merged**
